DROP TABLE IF EXISTS firmadanteklif.cities;
CREATE TABLE cities (city_id INTEGER PRIMARY KEY, name VARCHAR(30) NOT NULL);
INSERT INTO cities (city_id, name) VALUES
  (1, 'İstanbul'),
  (2, 'Ankara'),
  (3, 'İzmir'),
  (4, 'Adana'),
  (5, 'Adıyaman'),
  (6, 'Afyonkarahisar'),
  (7, 'Ağrı'),
  (8, 'Aksaray'),
  (9, 'Amasya'),
  (10, 'Antalya'),
  (11, 'Ardahan'),
  (12, 'Artvin'),
  (13, 'Aydın'),
  (14, 'Balıkesir'),
  (15, 'Bartın'),
  (16, 'Batman'),
  (17, 'Bayburt'),
  (18, 'Bilecik'),
  (19, 'Bingöl'),
  (20, 'Bitlis'),
  (21, 'Bolu'),
  (22, 'Burdur'),
  (23, 'Bursa'),
  (24, 'Çanakkale'),
  (25, 'Çankırı'),
  (26, 'Çorum'),
  (27, 'Denizli'),
  (28, 'Diyarbakır'),
  (29, 'Düzce'),
  (30, 'Edirne'),
  (31, 'Elazığ'),
  (32, 'Erzincan'),
  (33, 'Erzurum'),
  (34, 'Eskişehir'),
  (35, 'Gaziantep'),
  (36, 'Giresun'),
  (37, 'Gümüşhane'),
  (38, 'Hakkari'),
  (39, 'Hatay'),
  (40, 'Iğdır'),
  (41, 'Isparta'),
  (42, 'Kahramanmaraş'),
  (43, 'Karabük'),
  (44, 'Karaman'),
  (45, 'Kars'),
  (46, 'Kastamonu'),
  (47, 'Kayseri'),
  (48, 'Kırıkkale'),
  (49, 'Kırklareli'),
  (50, 'Kırşehir'),
  (51, 'Kilis'),
  (52, 'Kocaeli'),
  (53, 'Konya'),
  (54, 'Kütahya'),
  (55, 'Malatya'),
  (56, 'Manisa'),
  (57, 'Mardin'),
  (58, 'Mersin'),
  (59, 'Muğla'),
  (60, 'Muş'),
  (61, 'Nevşehir'),
  (62, 'Niğde'),
  (63, 'Ordu'),
  (64, 'Osmaniye'),
  (65, 'Rize'),
  (66, 'Sakarya'),
  (67, 'Samsun'),
  (68, 'Siirt'),
  (69, 'Sinop'),
  (70, 'Sivas'),
  (71, 'Şırnak'),
  (72, 'Tekirdağ'),
  (73, 'Tokat'),
  (74, 'Trabzon'),
  (75, 'Tunceli'),
  (76, 'Şanlıurfa'),
  (77, 'Uşak'),
  (78, 'Van'),
  (79, 'Yalova'),
  (80, 'Yozgat'),
  (81, 'Zonguldak');

DROP TABLE IF EXISTS firmadanteklif.categories;
CREATE TABLE categories (category_id INTEGER PRIMARY KEY, name VARCHAR(50) NOT NULL);
INSERT INTO categories (category_id, name) VALUES
  (1, 'Ev temizliği'),
  (2, 'Taşınma temizliği'),
  (3, 'Ofis temizliği'),
  (4, 'Mağaza temizliği'),
  (5, 'Apartman temizliği'),
  (6, 'İş yeri temizliği'),
  (7, 'Pencere temizliği'),
  (8, 'Zemin temizliği'),
  (9, 'Otel temizliği'),
  (10, 'Restorant temizliği'),
  (11, 'Depo temizliği'),
  (12, 'Halı & Perde temizliği'),
  (13, 'Araç temizliği'),
  (14, 'Elbise temizliği'),
  (15, 'Diğer temizlik'),

  (16, 'Ev taşıma'),
  (17, 'Eşya taşıma'),
  (18, 'Ofis taşıma'),
  (19, 'İş yeri taşıma'),
  (20, 'Depo taşıma'),
  (21,	'İnşaat malzeme taşıma'),
  (22, 'Diğer taşıma'),
  (23, 'Moloz taşıma'),

  (24, 'Banyo yenileme'),
  (25, 'Elektrik sistemi kurma'),
  (26, 'Marangoz servisi'),
  (27, 'Karo Fayans döşeme'),
  (28, 'Yerden ısıtma'),
  (29, 'Yalıtım'),
  (30, 'Mutfak yenileme'),
  (31, 'Boya badana'),
  (32, 'Mobilya montaj'),
  (33, 'Bina dış cephe tamir'),
  (34, 'Havalandırma'),
  (35, 'Çatı tamir'),
  (36, 'Temel atma'),
  (37, 'Kapı pencere'),
  (38, 'Duvar örme'),
  (39, 'Yıkım'),
  (40, 'Güneş enerjisi');